# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/eolmos/ECE-153A-Labs/Lab2B/Lab2B.srcs/sources_1/bd/system/ip/system_auto_ds_8/system_auto_ds_8.xci
# IP: The module: 'system_auto_ds_8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/eolmos/ECE-153A-Labs/Lab2B/Lab2B.srcs/sources_1/bd/system/ip/system_auto_ds_8/system_auto_ds_8_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_auto_ds_8'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/eolmos/ECE-153A-Labs/Lab2B/Lab2B.srcs/sources_1/bd/system/ip/system_auto_ds_8/system_auto_ds_8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_auto_ds_8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/eolmos/ECE-153A-Labs/Lab2B/Lab2B.srcs/sources_1/bd/system/ip/system_auto_ds_8/system_auto_ds_8.xci
# IP: The module: 'system_auto_ds_8' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/eolmos/ECE-153A-Labs/Lab2B/Lab2B.srcs/sources_1/bd/system/ip/system_auto_ds_8/system_auto_ds_8_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_auto_ds_8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/eolmos/ECE-153A-Labs/Lab2B/Lab2B.srcs/sources_1/bd/system/ip/system_auto_ds_8/system_auto_ds_8_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_auto_ds_8'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
